import Head from 'next/head'
import { Navbar } from 'views/Navbar'
import { Header } from 'views/Header'
import { Profile } from 'views/Profile'
import { Skills } from 'views/Skills'
import { Projects } from 'views/Projects'
import { Resume } from 'views/Resume'
import { Contact } from 'views/Contact'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Header />

      <main className='main'>
        <Profile />
        <Skills />
        <div className='divider mt-20 md:mt-24 lg:mt-28' />
        <Projects />
        <Resume />
        <Contact />
      </main>

      <footer className='bg-gray-600 mt-24 py-12 text-white'>
        <div className='container'>asad</div>
      </footer>
    </>
  )
}
