import Head from 'next/head'
import { Navbar } from 'views/Navbar'
import { Header } from 'views/Header'
import { Profile } from 'views/Profile'
import { Skills } from 'views/Skills'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Header />

      <main className='main'>
        <Profile />
        <Skills />
      </main>

      <footer className={'footer h-64'}>
        <h2>Footer</h2>
      </footer>
    </>
  )
}
